#!/usr/bin/env bash

ZARALAB_PHPPID=""

# magic function called by develo run helper
function _run_testserver_stop {
  __zaralab_detect_test_php
  if [ ! -z "$ZARALAB_PHPPID" ]; then
    kill $ZARALAB_PHPPID
    echo "PHP test server stopped"
  else
    _run_testserver_status
  fi
}

# magic function called by develo run helper
function _run_testserver_status {
  __zaralab_detect_test_php
  if [ -z "$ZARALAB_PHPPID" ]; then
    echo "PHP test server is not running"
  else
    echo "PHP test server is running on  http://127.0.0.1:8001/"
  fi
}

# magic function called by develo run helper
function _run_testserver {
  if [ ! -z "$1" ] && [ "$1" != "start" ]; then
    if [ "$1" != "help" ]; then
      echo "Unknown sub-command $1"
    fi
    __zaralab_test_server_help
    return 0
  fi
  __zaralab_detect_test_php
  if [ -z "$ZARALAB_PHPPID" ]; then
    nohup php -S 0.0.0.0:8001 -t tests/server tests/server/index.php > /dev/null 2>&1 &
    echo "PHP test server started on http://127.0.0.1:8001/"
  else
    _run_testserver_status
  fi
}

# local helper
function __zaralab_detect_test_php {
  ZARALAB_PHPPID=$(ps -ef | grep "php -S 0.0.0.0:8001 -t tests/server tests/server/index.php" | grep -v grep | awk '{print $2}')
}

function __zaralab_test_server_help {
  echo "Description: "
  echo "Starts built-in php server for application integration tests"
  echo
  echo "Usage: "
  echo "develo testserver [SUB-COMMAND]"
  echo
  echo "Sub-commands list: "
  echo "  start     Default, start local PHP test server"
  echo "  stop      Start local PHP test server"
  echo "  status    Check PHP local test server status"
  echo
}

# run
__develo_run_helper $@